# Generated by Django 5.0 on 2023-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_masuser_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='masuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masuser',
            name='isSuperAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
