# Generated by Django 5.0 on 2023-12-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_masuser_isadmin_masuser_issuperadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='masuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
