# Generated by Django 5.0 on 2023-12-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_masuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
