# Generated by Django 5.0 on 2023-12-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_masuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masuser',
            name='is_staff',
        ),
    ]
