# Generated by Django 5.0 on 2023-12-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_masuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='masuser',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
